const hcpOptions = [
    { value: 'allergist', label: 'Allergist' },
    { value: 'anesthesiologist', label: 'Anesthesiologist' },
    { value: 'audiologist', label: 'Audiologist' },
    { value: 'cardiologist', label: 'Cardiologist' },
    { value: 'chiropractor', label: 'Chiropractor' },
    { value: 'dentist', label: 'Dentist' },
    { value: 'dermatologist', label: 'Dermatologist' },
    { value: 'dietitian', label: 'Dietitian' },
    { value: 'emergency_medicine_physician', label: 'Emergency Medicine Physician' },
    { value: 'endocrinologist', label: 'Endocrinologist' },
    { value: 'epidemiologist', label: 'Epidemiologist' },
    { value: 'family_medicine_physician', label: 'Family Medicine Physician' },
    { value: 'gastroenterologist', label: 'Gastroenterologist' },
    { value: 'genetic_counselor', label: 'Genetic Counselor' },
    { value: 'geriatrician', label: 'Geriatrician' },
    { value: 'gynecologist', label: 'Gynecologist' },
    { value: 'hematologist', label: 'Hematologist' },
    { value: 'infectious_disease_specialist', label: 'Infectious Disease Specialist' },
    { value: 'internist', label: 'Internist' },
    { value: 'medical_geneticist', label: 'Medical Geneticist' },
    { value: 'microbiologist', label: 'Microbiologist' },
    { value: 'midwife', label: 'Midwife' },
    { value: 'neonatologist', label: 'Neonatologist' },
    { value: 'nephrologist', label: 'Nephrologist' },
    { value: 'neurologist', label: 'Neurologist' },
    { value: 'neurosurgeon', label: 'Neurosurgeon' },
    { value: 'nurse', label: 'Nurse' },
    { value: 'nurse_practitioner', label: 'Nurse Practitioner' },
    { value: 'nutritionist', label: 'Nutritionist' },
    { value: 'obstetrician', label: 'Obstetrician' },
    { value: 'occupational_therapist', label: 'Occupational Therapist' },
    { value: 'oncologist', label: 'Oncologist' },
    { value: 'ophthalmologist', label: 'Ophthalmologist' },
    { value: 'optometrist', label: 'Optometrist' },
    { value: 'orthodontist', label: 'Orthodontist' },
    { value: 'orthopedic_surgeon', label: 'Orthopedic Surgeon' },
    { value: 'otolaryngologist', label: 'Otolaryngologist' },
    { value: 'pathologist', label: 'Pathologist' },
    { value: 'pediatrician', label: 'Pediatrician' },
    { value: 'pharmacist', label: 'Pharmacist' },
    { value: 'physical_therapist', label: 'Physical Therapist' },
    { value: 'physician_assistant', label: 'Physician Assistant' },
    { value: 'plastic_surgeon', label: 'Plastic Surgeon' },
    { value: 'podiatrist', label: 'Podiatrist' },
    { value: 'psychiatrist', label: 'Psychiatrist' },
    { value: 'psychologist', label: 'Psychologist' },
    { value: 'pulmonologist', label: 'Pulmonologist' },
    { value: 'radiologist', label: 'Radiologist' },
    { value: 'registered_nurse', label: 'Registered Nurse' },
    { value: 'rheumatologist', label: 'Rheumatologist' },
    { value: 'surgeon', label: 'Surgeon' },
    { value: 'urologist', label: 'Urologist' },
    { value: 'veterinarian', label: 'Veterinarian' },
    { value: 'fitness_coach', label: 'Fitness Coach' }
  ]
const healthConditionOptions = [
    { value: 'diabetes_type_1', label: 'Diabetes Type 1' },
    { value: 'diabetes_type_2', label: 'Diabetes Type 2' },
    { value: 'obesity', label: 'Obesity' },
    { value: 'hypertension', label: 'Hypertension' },
    { value: 'heart_disease', label: 'Heart Disease' },
    { value: 'high_cholesterol', label: 'High Cholesterol' },
    { value: 'osteoporosis', label: 'Osteoporosis' },
    { value: 'polycystic_ovary_syndrome', label: 'Polycystic Ovary Syndrome' },
    { value: 'eating_disorders', label: 'Eating Disorders' },
    { value: 'arthritis', label: 'Arthritis' },
    { value: 'digestive_disorders', label: 'Digestive Disorders' },
    { value: 'cancer_recovery', label: 'Cancer Recovery' },
    { value: 'muscle_wasting_diseases', label: 'Muscle Wasting Diseases' },
    { value: 'metabolic_syndrome', label: 'Metabolic Syndrome' },
    { value: 'chronic_kidney_disease', label: 'Chronic Kidney Disease' },
    { value: 'asthma', label: 'Asthma' },
    { value: 'stroke_recovery', label: 'Stroke Recovery' },
    { value: 'traumatic_brain_injury', label: 'Traumatic Brain Injury' },
    { value: 'spinal_cord_injury', label: 'Spinal Cord Injury' },
    { value: 'chronic_pain', label: 'Chronic Pain' },
    { value: 'autoimmune_disorders', label: 'Autoimmune Disorders' },
    { value: 'chronic_obstructive_pulmonary_disease', label: 'Chronic Obstructive Pulmonary Disease' },
    { value: 'dementia_and_cognitive_disorders', label: 'Dementia and Cognitive Disorders' },
    { value: 'mood_disorders', label: 'Mood Disorders' },
    { value: 'anxiety_disorders', label: 'Anxiety Disorders' },
    { value: 'thyroid_disorders', label: 'Thyroid Disorders' },
    { value: 'skin_conditions', label: 'Skin Conditions (like Psoriasis and Eczema)' },
    { value: 'eye_conditions', label: 'Eye Conditions (like Glaucoma and Macular Degeneration)' },
    { value: 'hearing_loss_and_tinnitus', label: 'Hearing Loss and Tinnitus' },
    { value: 'infectious_diseases', label: 'Infectious Diseases (like Tuberculosis and HIV/AIDS)' },
    { value: 'liver_diseases', label: 'Liver Diseases' },
    { value: 'sleep_disorders', label: 'Sleep Disorders' },
    { value: 'wound_care_and_ulcer_management', label: 'Wound Care and Ulcer Management' },
    { value: 'bone_fractures_and_joint_replacements', label: 'Bone Fractures and Joint Replacements' },
    { value: 'rare_genetic_disorders', label: 'Rare Genetic Disorders' }
  ]
  
const selectOptions = {
    hcpOptions,
    healthConditionOptions
}
export default selectOptions